// autocad
#define ATRIM_STR "trim\n"
#define AEXT_STR "extend\n"
#define AMIRROR_STR "mirror\n"
#define AROTATE_STR "rotate\n"
#define AMOVE_STR "move\n"
#define ACOPY_STR "copy\n"
#define AFILLET_STR "fillet\n"
#define AOFFSET_STR "offset\n"
#define ALINE_STR "line\n"
#define ADIMENSION_STR "dim\n"
#define ARECTANGLE_STR "rectangle\n"
#define ACIRCLE_STR "circle\n"
#define APOLYLINE_STR "polyline\n"
#define ATEXT_STR "mtext\n"
#define AHATCH_STR "hatch\n"
#define ACHSPACE_STR "chspace\n"

// revi\nt
#define RCREATE_SIM_STR "cs"
#define RTRIM_STR "tr"
#define RMIRROR_STR "mm"
#define RROTATE_STR "ro"
#define RCOPY_STR "cc"
#define RDETAILLINE_STR "dl"
#define RBOX_STR "bx"
#define RTEXT_STR "tx"
#define RHIDE_STR "eh"
#define RSCALE_STR "sc"
#define RMOVE_STR "mv"
#define RDIMENSION_STR "di"
#define RVISIBILITY_STR "vv"
#define RALIGN_STR "al"